
import Footer from './components/Footer/Footer'
import Navbar from './components/Navbar/Navbar'
import './globals.css'

export const metadata = {
  title: 'Racine14 Tech',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <div className=''>
          {children}
        </div>
        <Footer />
      </body>
    </html>
  )
}
